appium:
  server: http://127.0.0.1:4723/wd/hub
  desired_caps:
    platformName: Android
    deviceName: emulator-5554  # 修改为真机序列号 adb devices 获取
    appPackage: com.tencent.mm
    appActivity: .ui.LauncherUI
    noReset: true  # 保持登录状态
    automationName: UiAutomator2
    newCommandTimeout: 300